
package User;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlo
 */
public class LandingPage extends javax.swing.JFrame {

    /** Creates new form LandingPage */
    public LandingPage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Hometxt = new javax.swing.JLabel();
        Logintxt = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        phonenum = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        emailpng = new javax.swing.JLabel();
        imageEmail = new javax.swing.JLabel();
        email2 = new javax.swing.JLabel();
        email3 = new javax.swing.JLabel();
        stPlaceholder = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        jLabel4.setText("Quezon City, Metro Manila, Philippines, 1117");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 550, 430, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/windows close.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 2, -1, -1));

        Hometxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Hometxt.png"))); // NOI18N
        Hometxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hometxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HometxtMouseClicked(evt);
            }
        });
        jPanel1.add(Hometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 120, 60));

        Logintxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Logintxt.png"))); // NOI18N
        Logintxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogintxtMouseClicked(evt);
            }
        });
        jPanel1.add(Logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 120, 60));

        email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email.setText("09182321911");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 260, 40));

        street.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        street.setText("J. Basa St., Brgy Sta. Lucia, Novaliches,");
        jPanel1.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 430, 40));

        phonenum.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        phonenum.setText("Phone:");
        jPanel1.add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 70, 40));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Header.png"))); // NOI18N
        header.setText("jLabel1");
        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        emailpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Phone.png"))); // NOI18N
        jPanel1.add(emailpng, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 50, 40));

        imageEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/email.png"))); // NOI18N
        jPanel1.add(imageEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 50, 40));

        email2.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        email2.setText("Email: ");
        jPanel1.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 70, 40));

        email3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email3.setText("haincuisine@gmail.com");
        jPanel1.add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 260, 40));

        stPlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Contact.png"))); // NOI18N
        jPanel1.add(stPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 520, 310));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Background.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1260, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HometxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HometxtMouseClicked
        this.setVisible(true);

    }//GEN-LAST:event_HometxtMouseClicked

    private void LogintxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogintxtMouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_LogintxtMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        ImageIcon smile = new ImageIcon(getClass().getResource("/LP_images/Smile.png"));
        ImageIcon exit = new ImageIcon(getClass().getResource("/LP_images/ExitIcon.png"));
        Object[] options = {"Yes", "No"};

        
        
        int response = JOptionPane.showOptionDialog(
                null, 
                "Do you want to exit?",
                "Hain Reservation System", 
                JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                exit,
                options,
                options[0] 
        );
        
        if(response == 0) {
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(null, "Enjoy Using the Application!", "Hain Reservation System", JOptionPane.INFORMATION_MESSAGE, smile);
        }
        
    }//GEN-LAST:event_ExitMouseClicked

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Hometxt;
    private javax.swing.JLabel Logintxt;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel emailpng;
    private javax.swing.JLabel header;
    private javax.swing.JLabel imageEmail;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phonenum;
    private javax.swing.JLabel stPlaceholder;
    private javax.swing.JLabel street;
    // End of variables declaration//GEN-END:variables
}
