/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Carlo
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form LandingPage */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        userTxt = new TextFieldUI.TextField();
        Hide = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        passHolder = new passwordfield.PasswordField();
        passTxt = new passwordfield.PasswordField();
        loginbtn = new button.Button();
        signUp = new javax.swing.JLabel();
        forgot = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/windows close.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 2, -1, -1));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/noUL.png"))); // NOI18N
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 45, 120, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/HomeUL.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 43, 120, 60));

        Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Header.png"))); // NOI18N
        Header.setText("jLabel1");
        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        userTxt.setForeground(new java.awt.Color(0, 0, 0));
        userTxt.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        userTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTxtFocusLost(evt);
            }
        });
        userTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTxtKeyPressed(evt);
            }
        });
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 410, 70));

        Hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/hide1.png"))); // NOI18N
        Hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HideMousePressed(evt);
            }
        });
        jPanel1.add(Hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/visible.png"))); // NOI18N
        eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eyeMouseReleased(evt);
            }
        });
        jPanel1.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        passHolder.setForeground(new java.awt.Color(151, 151, 151));
        passHolder.setText("Enter Password");
        passHolder.setEchoChar('\u0000');
        passHolder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passHolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passHolderMouseClicked(evt);
            }
        });
        passHolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passHolderKeyPressed(evt);
            }
        });
        jPanel1.add(passHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 410, 70));

        passTxt.setForeground(new java.awt.Color(0, 0, 0));
        passTxt.setEchoChar('*');
        passTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTxtFocusGained(evt);
            }
        });
        passTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTxtKeyTyped(evt);
            }
        });
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 410, 70));

        loginbtn.setBackground(new java.awt.Color(244, 242, 242));
        loginbtn.setText("Log In");
        loginbtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 240, 60));

        signUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Signup.png"))); // NOI18N
        signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 591, 190, 30));

        forgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/forgot.png"))); // NOI18N
        forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
        });
        jPanel1.add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 190, 30));

        text.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        text.setText("Doesn't have account?");
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 190, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/bg.png"))); // NOI18N
        Background.setText("jLabel1");
        Background.setOpaque(true);
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusGained
        if (userTxt.getText().equals("Enter Username")) {
            userTxt.setText("");
            userTxt.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_userTxtFocusGained

    private void userTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusLost
        if (userTxt.getText().equals("")) {
            userTxt.setText("Enter Username");
            userTxt.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_userTxtFocusLost

    private void passTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtKeyTyped
        passHolder.setVisible(false);
        if (passTxt.getText().isEmpty()) {
            passHolder.setVisible(true);
        }
    }//GEN-LAST:event_passTxtKeyTyped

    private void userTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTxtKeyPressed

        userTxt.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_userTxtKeyPressed

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
        loginbtn.setBackground(new Color(153, 255, 153));
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        loginbtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_loginbtnMouseExited

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        Login.setVisible(true);
    }//GEN-LAST:event_LoginMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        LandingPage lp = new LandingPage();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void passTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtKeyPressed
        passHolder.setVisible(false);
        passTxt.setVisible(true);
    }//GEN-LAST:event_passTxtKeyPressed

    private void passHolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passHolderMouseClicked
        passHolder.setVisible(false);
        passTxt.setVisible(true);

    }//GEN-LAST:event_passHolderMouseClicked

    private void eyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseReleased
        Hide.setVisible(true);
        eye.setVisible(false);
        passTxt.setEchoChar('*');
    }//GEN-LAST:event_eyeMouseReleased

    private void HideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMousePressed
        Hide.setVisible(false);
        eye.setVisible(true);
        passTxt.setEchoChar((char) 0);
    }//GEN-LAST:event_HideMousePressed

    private void passHolderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passHolderKeyPressed
        passHolder.setVisible(false);
        passTxt.setVisible(true);
    }//GEN-LAST:event_passHolderKeyPressed

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        ForgotPassword fp = new ForgotPassword();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_forgotMouseClicked

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked
        SignUp signup = new SignUp();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_signUpMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        ImageIcon smile = new ImageIcon(getClass().getResource("/LP_images/Smile.png"));
        ImageIcon exit = new ImageIcon(getClass().getResource("/LP_images/ExitIcon.png"));
        Object[] options = {"Yes", "No"};

        int response = JOptionPane.showOptionDialog(
                null,
                "Do you want to exit?",
                "Hain Reservation System",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                exit,
                options,
                options[0]
        );

        if (response == 0) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Enjoy Using the Application!", "Hain Reservation System", JOptionPane.INFORMATION_MESSAGE, smile);
        }

    }//GEN-LAST:event_ExitMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        ImageIcon error = new ImageIcon(getClass().getResource("/LP_images/Error_1.png"));
        
        
        String username, password, query;

        if ("".equals(passTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Password is required!", "Registration", JOptionPane.ERROR_MESSAGE, error);
            return;
        }
        

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/haindatabase", "root", "carlo123");

            username = userTxt.getText();
            password = String.valueOf(passTxt.getPassword());

            query = "SELECT * FROM useraccounts WHERE BINARY username = ? AND BINARY password = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                AccountInfo accounts = new AccountInfo();
                accounts.setUsername(rs.getString("Username"));
                accounts.setPassword(rs.getString("Password"));
                accounts.setSecurityQuestion(rs.getString("SecurityQuestion"));
                accounts.setSecurityAnswer(rs.getString("Answers"));

                dispose();
                Dashboard db = new Dashboard(accounts);
                db.setVisible(true);
                db.showPanel("Table");
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or password", "Login", JOptionPane.INFORMATION_MESSAGE, error);
            }
        } catch (Exception e) {
            System.out.print("ERROR!");
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void passTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFocusGained
        if (passTxt.getText().equals("Enter Password")) {
            passTxt.setText("");
        }
    }//GEN-LAST:event_passTxtFocusGained

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Hide;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel forgot;
    private javax.swing.JPanel jPanel1;
    private button.Button loginbtn;
    private passwordfield.PasswordField passHolder;
    private passwordfield.PasswordField passTxt;
    private javax.swing.JLabel signUp;
    private javax.swing.JLabel text;
    private TextFieldUI.TextField userTxt;
    // End of variables declaration//GEN-END:variables
}
