package User;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;

/**
 *
 * @author Carlo
 */
public class SignUp extends javax.swing.JFrame {

    /** Creates new form LandingPage */
    public SignUp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        passTxt = new textfield.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passHide = new javax.swing.JLabel();
        passVisible = new javax.swing.JLabel();
        conPassTxt = new textfield.PasswordField();
        passHide1 = new javax.swing.JLabel();
        passVisible1 = new javax.swing.JLabel();
        userTxt = new textfield.TextField();
        answer = new textfield.TextField();
        signUp = new button.Button();
        secuQuestion = new combobox.Combobox();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Logintxt.png"))); // NOI18N
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 43, 120, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/HomeUL.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 43, 120, 60));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/windows close.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 2, -1, -1));

        Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Header.png"))); // NOI18N
        Header.setText("jLabel1");
        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        passTxt.setEchoChar('*');
        passTxt.setLabelText("Password");
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 335, 400, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel1.setText("Already have account?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 633, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/sLogin.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 634, 90, 30));

        passHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/bigHide.png"))); // NOI18N
        passHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passHideMousePressed(evt);
            }
        });
        jPanel1.add(passHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 340, 30, -1));

        passVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/bigVisible.png"))); // NOI18N
        passVisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passVisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passVisibleMouseReleased(evt);
            }
        });
        jPanel1.add(passVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 340, -1, -1));

        conPassTxt.setEchoChar('*');
        conPassTxt.setLabelText("Confirm Password");
        jPanel1.add(conPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 395, 400, 50));

        passHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/bigHide.png"))); // NOI18N
        passHide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passHide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passHide1MousePressed(evt);
            }
        });
        jPanel1.add(passHide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 400, -1, -1));

        passVisible1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/bigVisible.png"))); // NOI18N
        passVisible1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passVisible1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passVisible1MouseReleased(evt);
            }
        });
        jPanel1.add(passVisible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 400, -1, -1));

        userTxt.setLabelText("Username");
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 275, 400, 50));

        answer.setLabelText("Your Answer");
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 515, 400, 50));

        signUp.setText("Sign Up");
        signUp.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpMouseExited(evt);
            }
        });
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 575, 240, 60));

        secuQuestion.setMaximumRowCount(10);
        secuQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is the name of your favorite pet?", "What high school did you attend?", "In what city were you born?", "What was the name of your elementary school?", "What is your dream job?" }));
        secuQuestion.setSelectedIndex(-1);
        secuQuestion.setLabeText("Security Question");
        jPanel1.add(secuQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 455, 400, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LP_images/Does have account.png"))); // NOI18N
        Background.setOpaque(true);
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_LoginMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        LandingPage lp = new LandingPage();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void passHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passHideMousePressed
        passHide.setVisible(false);
        passVisible.setVisible(true);
        passTxt.setEchoChar((char) 0);
    }//GEN-LAST:event_passHideMousePressed

    private void passVisibleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passVisibleMouseReleased
        passHide.setVisible(true);
        passVisible.setVisible(false);
        passTxt.setEchoChar('*');
    }//GEN-LAST:event_passVisibleMouseReleased

    private void passHide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passHide1MousePressed
        passHide1.setVisible(false);
        passVisible1.setVisible(true);
        conPassTxt.setEchoChar((char) 0);
    }//GEN-LAST:event_passHide1MousePressed

    private void passVisible1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passVisible1MouseReleased
        passHide1.setVisible(true);
        passVisible1.setVisible(false);
        conPassTxt.setEchoChar('*');
    }//GEN-LAST:event_passVisible1MouseReleased

    private void signUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseEntered
        signUp.setBackground(new Color(153, 255, 153));
        signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signUpMouseEntered

    private void signUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseExited
        signUp.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_signUpMouseExited


    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        ImageIcon smile = new ImageIcon(getClass().getResource("/LP_images/Smile.png"));
        ImageIcon exit = new ImageIcon(getClass().getResource("/LP_images/ExitIcon.png"));
        Object[] options = {"Yes", "No"};

        int response = JOptionPane.showOptionDialog(
                null,
                "Do you want to exit?",
                "Hain Reservation System",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                exit,
                options,
                options[0]
        );

        if (response == 0) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Enjoy Using the Application!", "Hain Reservation System", JOptionPane.INFORMATION_MESSAGE, smile);
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/haindatabase", "root", "carlo123");

            if ("".equals(userTxt.getText())) {
                JOptionPane.showMessageDialog(null, "Username is required!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if ("".equals(passTxt.getText())) {
                JOptionPane.showMessageDialog(null, "Password is required!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if ("".equals(conPassTxt.getText())) {
                JOptionPane.showMessageDialog(null, "Confirm Password is required!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if (passTxt.getText().length() < 6) {
                JOptionPane.showMessageDialog(null, "Password must be at least 6!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if (!passTxt.getText().equals(conPassTxt.getText())) {
                JOptionPane.showMessageDialog(null, "Password does not match!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if (secuQuestion.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Choose Your Security Question!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else if ("".equals(answer.getText())) {
                JOptionPane.showMessageDialog(null, "Provide an Answer!", "Registration", JOptionPane.ERROR_MESSAGE, null);
            } else {

                String checkUserQuery = "SELECT COUNT(*) FROM useraccounts WHERE Username = ?";
                PreparedStatement checkUserPst = con.prepareStatement(checkUserQuery);
                checkUserPst.setString(1, userTxt.getText());
                ResultSet rs = checkUserPst.executeQuery();
                rs.next();
                if (rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Username is already taken!", "Registration", JOptionPane.ERROR_MESSAGE, null);
                } else {

                    AccountInfo accounts = new AccountInfo();
                    accounts.setUsername(userTxt.getText());
                    accounts.setPassword(passTxt.getText());
                    accounts.setConfirmPass(conPassTxt.getText());
                    accounts.setSecurityQuestion(secuQuestion.getSelectedItem().toString());
                    accounts.setSecurityAnswer(answer.getText());

                    String query = "INSERT INTO useraccounts (Username, Password, ConfirmPassword, SecurityQuestion, Answers) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setString(1, accounts.getUsername());
                    pst.setString(2, accounts.getPassword());
                    pst.setString(3, accounts.getConfirmPass());
                    pst.setString(4, accounts.getSecurityQuestion());
                    pst.setString(5, accounts.getSecurityAnswer());

                    pst.executeUpdate();

                    ImageIcon smile = new ImageIcon(getClass().getResource("/LP_images/Smile.png"));
                    JOptionPane.showMessageDialog(null, "Account has been successfully created!", "Registration", JOptionPane.PLAIN_MESSAGE, smile);

                    System.out.println("SUCCESS!");

                    userTxt.setText("");
                    passTxt.setText("");
                    conPassTxt.setText("");
                    secuQuestion.setSelectedIndex(-1);
                    answer.setText("");
                }
            }

        } catch (Exception e) {
            System.out.print("ERROR!");
        }
    }//GEN-LAST:event_signUpActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private textfield.TextField answer;
    private textfield.PasswordField conPassTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passHide;
    private javax.swing.JLabel passHide1;
    private textfield.PasswordField passTxt;
    private javax.swing.JLabel passVisible;
    private javax.swing.JLabel passVisible1;
    private combobox.Combobox secuQuestion;
    private button.Button signUp;
    private textfield.TextField userTxt;
    // End of variables declaration//GEN-END:variables
}
